### ISSUE TITLE
[FEATURE] Get root agent id by calling the get config api in ml-commons

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/dashboards-assistant#127]
**Is your feature request related to a problem?**
Now there's an api called get config api in ml-commons plugin, which can be used to get the root agent id, we need to refactor the code of getting root agent id, call that api directly to get the id instead of reading the name of the agent from the yml file.

**What solution would you like?**
Refactor the code.

**What alternatives have you considered?**
nothing

**Comment by xluo-aws** [comment]
Can this ticket be closed?

**Comment by gaobinlong** [comment]
> Can this ticket be closed?

Yeah, it can be closed as completed yet.

**Comment by gaobinlong** [comment]
Closed by #128 .
