### ISSUE TITLE
[FEATURE]Fetch chatbot root agent id before execution

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/dashboards-assistant#154]
**Is your feature request related to a problem?**
The current implementation is only retrieve root agent id if execution fails with resource node found error. The reason is that the get root agent id API is heavy because it need to loop through all agents to match the root agent name. It impacts user experience, admin need to remember to deprovision the current root agent to make the new one take effect. 

**What solution would you like?**
The new solution is to call get root agent id every time before execute the agent. The get root agent id is enhanced with a very light implementation so performance and latency is no longer a concern.

**What alternatives have you considered?**
Keep the current logic

**Do you have any additional context?**
No

**Comment by gaobinlong** [comment]
Closed by https://github.com/opensearch-project/dashboards-assistant/pull/165.
