### ISSUE TITLE
Replace hardcode dockBottom and dockRight icon with OUI 

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/dashboards-assistant#157]
Replace 
https://github.com/opensearch-project/dashboards-assistant/blob/main/public/tabs/chat_window_header.tsx#L22

with 
https://oui.opensearch.org/1.5/#/display/icons

**Comment by raintygao** [comment]
@Hailong-am As I checked the code, I  think this issue has been completed in 2.13, right?

**Comment by Hailong-am** [comment]
> @Hailong-am As I checked the code, I think this issue has been completed in 2.13, right?

should resolve by the sidecar PR #164, we can close it
