### ISSUE TITLE
[FEATURE] Support context aware alert analysis

### ISSUE THREAD

**Issue by songkant-aws** [opensearch-project/dashboards-assistant#214]
**Is your feature request related to a problem?**
Support in-context prompting experience for other dashboard plugins like alerts. Today, we see “in-context prompting” as an action a user can take on the fly quickly and easily.

**What solution would you like?**
By reusing existing IncontextInsight component, we can easily wrap it around the children component like alert column to pass context to llm and expects the summarization response from llm. For now, we only support one click to generate summary. The message action bars will be supported in next iteration with some code refactoring.

**Do you have any additional context?**
In-context prompting for alerts entry point:
<img width="465" alt="Screenshot 2024-07-12 at 14 28 18" src="https://github.com/user-attachments/assets/a1fda9e9-c87f-415f-91ff-6acc654b184b">
In-context prompting generating process:
<img width="485" alt="Screenshot 2024-07-12 at 14 28 23" src="https://github.com/user-attachments/assets/0b60cedd-3bd9-490e-bf93-cf261a3f279f">
In-context prompting showing summary result with option to continue the conversation in chat:
<img width="562" alt="Screenshot 2024-07-12 at 14 28 06" src="https://github.com/user-attachments/assets/3094597d-7a33-4bc6-ae14-383c49ea62a4">

**Comment by dblock** [comment]
@songkant-aws Does #215 close this?

[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/amistrn)]

**Comment by songkant-aws** [comment]
> @songkant-aws Does #215 close this?
> 
> [Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/amistrn)]

Yes, we can close this issue with [#215](https://github.com/opensearch-project/dashboards-assistant/pull/215).
